# Generated by Django 4.2.6 on 2023-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("string1", models.CharField(max_length=10)),
                ("string2", models.CharField(max_length=10)),
                ("number1", models.IntegerField()),
                ("number2", models.IntegerField()),
            ],
        ),
    ]
