# Generated by Django 4.2.6 on 2023-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0002_mymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mymodel",
            name="number1",
        ),
        migrations.RemoveField(
            model_name="mymodel",
            name="number2",
        ),
        migrations.AddField(
            model_name="mymodel",
            name="create_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="edit_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="mymodel",
            name="result",
            field=models.TextField(null=True),
        ),
    ]
